
# Netlify configuration file

# Build settings
[build]
  # Directory containing the built site (the output of npm run build)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all URLs to index.html so that the React router can handle them
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper caching and security
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"

# Specific cache control for index.html to ensure fresh reloads
[[headers]]
  for = "/index.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
