// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whdugcvcrjhjogstrcak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZHVnY3Zjcmpoam9nc3RyY2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjkzMTEsImV4cCI6MjA1NzkwNTMxMX0.zXvflX0ifzHkHPLNyjtA_ncogII7UxVnYXPx6f_rQ4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);